import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

import Header from "../components/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Guilds</h1>
        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/</code>
          and
          <code className={styles.code}>components/</code>!
        </p>
      </main>
    </div>
  );
}
